# -*- coding: utf-8 -*-
"""Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ug4Ox4qIFDSo1koFA0XiNJE-ce12rECy

# Proyek Analisis Data: Bike Sharing Dataset
- **Nama:** Nuhaa Salsabila Shidqiyyah
- **Email:** nuhaa.22045@mhs.unesa.ac.id
- **ID Dicoding:** nuhaasalsabila

## Menentukan Pertanyaan Bisnis

- Bagaimana pengaruh musim terhadap jumlah penyewaan sepeda per tahun?
- Bagaimana perbedaan penyewaan sepeda pada hari kerja dan hari libur?

## Import Semua Packages/Library yang Digunakan
"""

pip install streamlit

import numpy as np #untuk menghitung komputasi
import pandas as pd #untuk manipulasi dan analisis data
import matplotlib.pyplot as plt #untuk visualisasi
import seaborn as sns #sama untuk visualisasi

"""## Data Wrangling

### Gathering Data
"""

hari = pd.read_csv("day.csv")
hari.head()

jam = pd.read_csv("hour.csv")
jam.head()

"""**Insight:**
- Pada data 1 dapat dilihat datanya yang kolomnya terdiri dari instant, dteday, season, yr, mnth, holiday, weekday, workingday, weathersit, temp, atemp, hum, windspeed, casual, registered, cnt
- Pada data 2 instant, dteday, season, yr, mnth, hr, holiday, weekday, workingday, weathersit, temp, atemp, hum, windspeed, casual, registered, cnt
Kesimpulan Sementara : pada data 2 ada tambahan kolom hour

### Assessing Data

CSV DAY
"""

hari.info()

"""Terdapat kolom yang tidak sesuai, seperti dteday harusnya memiliki tipe datetime karena berisi tanggal"""

hari.isna().sum() #tidak memiliki missing value

print ("Jumlah duplikasi data pada jam.csv adalah :", hari.duplicated().sum()) #tidak memiliki duplikat

hari.nunique()

hari.describe()

"""Dataset menunjukkan bahwa penyewaan sepeda lebih tinggi pada hari kerja dibandingkan dengan hari libur. Sebagian besar penyewa adalah pengguna terdaftar dari total penyewa yang ada. Selain itu, suhu yang lebih baik dan kelembapan yang sedang juga berkontribusi pada peningkatan jumlah penyewaan sepeda. Maka dari itu, penyewaan sepeda dipengaruhi oleh hari kerja dan kondisi cuaca yang baik.

CSV JAM
"""

jam.info()

"""sama seperti data day.csv, kolom dtedat bukan bertipe date time."""

jam.isna().sum() #no missing value bagus

print ("Jumlah duplikasi data pada jam.csv adalah :", jam.duplicated().sum()) #tidak da uplikat juga

jam.nunique()

jam.describe()

"""Pada data ini menunjukkan bahwa penyewaan sepeda lebih tinggi pada hari kerja dan pada jam tertentu, dengan mayoritas pengguna terdaftar. Selain itu, kondisi cuaca yang baik, terutama suhu dan kelembapan, mempengaruhi jumlah penyewaan.

**Insight:**
- beberapa data tidak sesuai dan harus diganti tipe datanya
- data yang cukup bersih karena tidak memiliki baris kosong dan tidak ada duplikasi data

### Cleaning Data
"""

#merubah tipe data dteday pada var hari
hari['dteday'] = pd.to_datetime(hari['dteday'])
hari.info()

#merubah tipe data dteday pada var hari
jam['dteday'] = pd.to_datetime(jam['dteday'])
jam.info()

"""**Insight:**
- Beberapa kolom sudah diubah sesuai dengan tipe datanya

## Exploratory Data Analysis (EDA)
"""

#DROP KOLOM YANG TIDKA DIBUTUHKAN
hari.drop(['instant', 'dteday', 'mnth', 'holiday', 'weekday', 'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered'], axis=1, inplace=True)
hari.head()

#MENGGANTI NAMA KOLOM AGAR MUDAH DIBACA
hari.rename(columns={
    'yr' : 'year',
    'cnt' : 'total'
}, inplace=True)
hari.head()

#MENGUBAH LABEL SEASON DENGAN STRING SESUAI DENGAN MUSIM
hari.loc[hari['season'] == 1, 'season'] = 'Winter'
hari.loc[hari['season'] == 2, 'season'] = 'Spring'
hari.loc[hari['season'] == 3, 'season'] = 'Summer'
hari.loc[hari['season'] == 4, 'season'] = 'Fall'
hari.head()

"""JAM.CSV"""

#DROP KOLOM
jam.drop(['instant', 'dteday', 'season', 'yr', 'hr','holiday', 'weekday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered'], axis=1, inplace=True)
jam.head()

#MENGGANTI NAMA KOLOM AGAR MUDAH DIBACA
jam.rename(columns={
    'mnth' : 'month',
    'yr' : 'year',
    'cnt' : 'total'
}, inplace=True)
jam.head()

"""## Insight :
- Pada day.csv beberapa kolom tidak dibutuhkan mengingat tujuan yang dicari hanya pengaruh musim terhadap penyewaan. Maka kolom yang dipakai adalah season sebagai musim, year karena melihat hasil per tahun, dan total dari penyewa sepeda
- Pada hour.csv juga menghapus beberapa kolom karena hanya ingin menghitung jumlah penyewa sepeda pada hati kerja dan tidak. Jadi kolom yang dipakai month karena menghitung per bulan, working day karena hari kerja dan lainnya tidak dihitung, begitupun kolom total digunakan untuk menghitung jumlah penyewa.
- pada dua csv ini mengganti nama kolom agar tida menimbulkan bias dan biar jelas.

### Explore

day
"""

hari.groupby(by=['year', 'season']).agg({
    'total': ['sum', 'max', 'min', 'mean']
})

result_hari = hari.groupby(['year', 'season'])['total'].sum().reset_index()

"""jam"""

jam.groupby(by=['month', 'workingday']).agg({
    'total': ['sum', 'max', 'min', 'mean']
})

result_jam = jam.groupby(['month', 'workingday'])['total'].sum().reset_index()

"""**Insight:**
- Mengelompokkan tahun dan musim yang terjadi dan menjumlahkan total jumlah penyewa dan disimpan pada variabel result_hari. Sehingga pada proses visualisasi hanya memanggil nama variabel begitupun pada hour.csv.

## Visualization & Explanatory Analysis

### Pertanyaan 1:

Bagaimana pengaruh musim terhadap jumlah penyewaan sepeda per tahun?
"""

# Membuat plot menggunakan seaborn
plt.figure(figsize=(10,6))
sns.barplot(data=result_hari, x='year', y='total', hue='season')

# Menambahkan judul dan label
plt.title('Pengaruh Musim per Tahun terhadap Jumlah Penyewaan Sepeda', fontsize=14)
plt.xlabel('Tahun', fontsize=12)
plt.ylabel('Jumlah Penyewaan Sepeda', fontsize=12)
plt.legend(title='Musim')
plt.xticks(rotation=45)

# Menampilkan plot
plt.tight_layout()
plt.show()

"""### Pertanyaan 2: Bagaimana perbedaan penyewaan sepeda pada hari kerja dan hari libur?"""

# Membuat plot menggunakan seaborn
plt.figure(figsize=(10,6))
sns.barplot(data=result_jam, x='month', y='total', hue='workingday')

# Menambahkan judul dan label
plt.title('Total Penyewaan Sepeda pada Hari Kerja dan Hari Libur', fontsize=14)
plt.xlabel('Bulan', fontsize=12)
plt.ylabel('Jumlah Penyewaan Sepeda', fontsize=12)
plt.legend(title='Hari Kerja (1) vs Hari Libur (0)')
plt.xticks(rotation=45)

# Menampilkan plot
plt.tight_layout()
plt.show()

"""**Insight:**
- number 1

The effect of seasonality on the number of bicycle rentals shows a different trend between 2011 and 2012. In winter (January-February), the number of rentals is lowest due to cold weather, but 2012 showed an increase over 2011. Although winter conditions are less than ideal for cycling, there are signs of growing interest in the second year. Spring (March-May) saw an increase in rentals, especially in May when the weather started to improve. 2012 saw a higher number of rentals, indicating a growth in popularity of bike sharing compared to 2011.

In summer (June-August), rentals peak in August, with a significant increase in 2012. This may be due to the increased popularity of the service, more outdoor events, and better accessibility, rather than too-hot temperatures discouraging cycling. In **fall** (September-November), rentals start to decline from the summer peak, but numbers are still quite high. 2012 continued to show larger numbers than 2011, with cooler weather that was still comfortable for cycling.

Overall, the number of bicycle rentals increased from 2011 to 2012 in all seasons, with summer being the highest peak, likely due to increased popularity, better service accessibility, and more favorable weather.

- number 2

Based on the bicycle rental comparison chart between weekdays and holidays, it can be seen that holiday rentals tend to be much higher than weekdays, especially in the spring to summer months. Peak holiday bike rentals occur in August, with over 250,000 bikes rented, far exceeding the number of weekday rentals.
During the spring to summer months (March to August), holiday bike rentals increase sharply, possibly because more people take advantage of the nice weather for leisure cycling. In contrast, weekday rentals are more stable and relatively lower, although there are moderate increases in the summer months such as July and August.
In the fall and winter months (September to February), bicycle rentals decrease on both weekdays and holidays, but holiday rentals remain higher. The difference in rentals between weekdays and holidays is most pronounced in summer, when people are more likely to cycle on holidays for recreation or outdoor activities.

Overall, holidays are clearly more popular for bike rentals, especially in seasons with favorable weather, while weekday rentals remain stable but lower.

## Analisis Lanjutan (Opsional)

## Conclusion

- Conclution pertanyaan 1
The number of bicycle rentals increased from 2011 to 2012 in all seasons. Although winter had the lowest number of rentals, there was an increase in 2012 indicating growing interest. Spring also recorded an increase, especially in May. In summer, rentals peak in August, with a significant spike in 2012 due to the increasing popularity and accessibility of the service. Meanwhile, the fall season continued to show high numbers despite a decline from the summer peak. Overall, the trend shows growth in bike rentals thanks to more favorable weather and better services.
- Conclution pertanyaan 2
The analysis shows that bicycle rentals on holidays are much higher than those on weekdays, especially from spring to summer. The peak of bicycle rentals occurs in August, with more than 250,000 bicycles rented on holidays. During March to August, holiday bike rentals increase sharply, possibly because the good weather encourages people to cycle. In contrast, weekday bicycle rentals tend to be stable and lower, although there is a moderate increase in July and August. In the fall and winter, bicycle rentals decline on both types of days, but rentals on holidays remain higher. Overall, holidays are a more popular time to rent a bicycle, especially in seasons with favorable weather.
"""